# Generated by Django 3.0.4 on 2020-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=200)),
                ('Course_Description', models.CharField(max_length=500)),
                ('Course_Information', models.TextField()),
                ('Additional_Information', models.URLField(max_length=250)),
            ],
        ),
    ]
