# Generated by Django 3.0.4 on 2020-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Additional_Information',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Course_Information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
